### PR TITLE
Add Rancher-specific tolerations to daemonset manifests

### PR DESCRIPTION
**Pull request by ironashram**
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

https://github.com/rancher/rancher/commit/5f6a1b857da7a61d4d9bd1e697b8ce14d8cf54e9

### CODE REVIEW

**Review by aroberts87 — APPROVED** [review]
lgtm

**Comment by nathan-b** [comment]
Is there any possibility that these manifests could have a negative interaction with non-Rancher hosts? Since we don't have a specific daemonset just for rancher, I have a concern about unintended consequences.

**Comment by ironashram** [comment]
> Is there any possibility that these manifests could have a negative interaction with non-Rancher hosts? Since we don't have a specific daemonset just for rancher, I have a concern about unintended consequences.

not really, the daemonset will just have some unnecessary tolerations defined if it's not Rancher, but i'm not aware of any possible issue caused by that, except that it's a bit ugly

**Review by nathan-b — APPROVED** [review]
Thanks for the change and for addressing my question! Approving and merging.

**Pull request merged**
