### PR TITLE
add support elementary os hera install-agent-k8s.sh

### PR DESCRIPTION
**Pull request by okutasan**
i'm add fix for elementaryOS Hera.
previously i got error Unsupported operating system. Try using the manual installation instructions when install at ElementaryOS Hera 5.

Thankyou if you accept my pull request

### CODE REVIEW

**Comment by nathan-b** [comment]
Hi @okutasan -- thanks for the PR! Does the agent run fine under ElementaryOS?

**Comment by okutasan** [comment]
> Hi @okutasan -- thanks for the PR! Does the agent run fine under ElementaryOS?

hi @nathan-b  . Yes , the agent is running well on elementary-os hera 5.1.7. 
i include the detailed version elementary that im using 
Screenshot from 2021-05-14 21 46 18

**Comment by nathan-b** [comment]
@okutasan Is there a reason you made the change to the IKS install script? Are you somehow running an elementaryOS node inside IBM's k8s service?

**Comment by nathan-b** [comment]
@okutasan Following up on the above message...is there a reason you made this change for IKS? Or should we migrate it to kubernetes?

**Pull request closed without merging**
