### PR TITLE
Change: Update LDAP config (NOTE: DO NOT MERGE. Phil will do it timed with on-prem release & doc changes!)

### PR DESCRIPTION
**Pull request by alexgallotta**
Added flag to enable LDAP login.
To enable api user creation, another endpoint must be hit so probably the flow in the scripts must be changed.
Documentation on where the new endpoint is is here https://sysdig.atlassian.net/wiki/spaces/EN/pages/167116851/LDAP+API+configuration#LDAPAPIconfiguration-API

### CODE REVIEW

**Comment by philrz** [comment]
NOTE: Please! Even if someone reviews & approves this PR, **do not** jump right to merging it! Since the merge reveals it to the public, we need the merge to coincidence with the next on-prem release going GA and the corresponding doc changes that reference these script updates. Since I'm tracking the on-prem release & working on the doc changes, I'll take care of that merge if that's ok with everyone. Thanks!

@alexgallotta: Yes, thanks for getting this kicked off. I need to make more enhancements as well. If it's ok, I may just use this branch to pile on everything else. Right now that checklist includes:

- An example that shows the referral chasing options
- Add a `.sh` extension to all the shell scripts
- Use `/usr/bin/env bash` in the hash-bang line (@mbreitung suggestion)
- Address some of @mbreitung's other critiques from the last time he reviewed this (we let them slide at the time)

If anyone can think of other additions/changes, please speak up, as I expect to be working on them today (& tomorrow/weekend if necessary depending on how much other bug fixes & verification slow me down.)

**Comment by philrz** [comment]
@alexgallotta: I've restored the `settings_login_with_user_create.json` after confirming in the on-prem build #949 (which is very close/equivalent to what's about to go GA) that the setting has not yet moved to the separate `api/admin/appAttribute/apiUserCreation` endpoint. I know you indicated in your docs it would be moved there as of #932 & after, but that was a build based on your branch with all the SAML+LDAP work, and hence it seems you made that statement on the assumption everything from that branch would be going into this next GA on-prem release, which is no longer the case.

**Comment by philrz** [comment]
I've got all the changes needed to these scripts now committed to this branch and the corresponding doc changes that reference them are staged as "Unpublished Changes" on the docs site at https://sysdigdocs.atlassian.net/wiki/spaces/LDAP/pages/203620377/LDAP+Authentication+Configuration. When the final release goes GA, I'll update the release build # on that doc page (I've taken a guess and put the as-yet-build number #951 there as a placeholder) and plan to merge this PR at the same time I click Publish on that page.

@mbreitung: I'd appreciate a review when you get a chance, as this includes some of your feedback from last time I asked you to review these.

**Comment by philrz** [comment]
Thanks for the approval @mbreitung! Per the note above, I'm now going to hold this PR in an "open" state and time the merge to coincide with the release going GA and the docs being published. Stay tuned.

**Comment by philrz** [comment]
GA build #963 is out and updated docs are published. Merging this PR.

**Comment by alexgallotta** [comment]
@philrz I can't tell about the next GA, but when the Cisco-feature branch will be merged to staging (I suppose today or tomorrow) the LDAP API call with
`allowApiUserCreation`
will throw error

**Pull request merged**
